# workflow that tests and quality-checks app on pull requests
name: Test

on: workflow_dispatch

jobs:
  # only install yarn packages once for rest of jobs
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: mkdirInstall packages
        run: |
          mkdir jeff
          touch jeff/ffej.txt
      - name: make another forder
        run: |
          mkdir ffej
          touch ffej/ffej-${{ github.run_id }}.txt
      - name: Store cache
        uses: actions/cache@v2
        with:
          path: ffej
          key: ci-${{ github.run_id }}-${{ github.run_number }}

  # test that app is properly formatted and linted
  test-lint:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ffej
          key: ci-${{ github.run_id }}-${{ github.run_number }}
      - name: Run test
        run: |
          echo $(ls -a ffej)
