name: A workflow for my hello world file
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo {{ github.run_id }}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo $(ls)
        DOCKER_BUILDKIT=1 docker build \
        -t rubikloud/ml_demandsensing:dev-base \
        .
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo echo $(ls /var/lib)
  build:
    needs: job3
    uses: sagniksom/hello-github-actions/.github/workflows/on_call.yml@main
    with:
      username: mona
