name: A workflow for my hello world file
on: workflow_dispatch
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make jeff
        id: make
        run: |
          mkdir jeff
          cd jeff
          touch ffej.txt
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/jeff
          key: jeff
  echo:
    name: echo action
    runs-on: ubuntu-latest
    steps:
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/jeff
          key: jeff
      - if: ${{ jobs.build.steps.cache.outputs.cache-hit != false }}
        name: Echo
        run: |
          cd jeff
          ls
