name: on_call

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  reusable_workflow_job:
  runs-on: ubuntu-latest
  steps:
    - name: echo
      runs: |
        echo ${{ inputs.username }}
